#! /usr/bin/env python

def options(opt):
    opt.load("compiler_c")
    opt.load("gir", tooldir="..")

def configure(cnf):
    cnf.load("compiler_c")
    cnf.load("gir", tooldir="..")
    cnf.check_gir('GLib-2.0')

def build(bld):
    bld(features="c cshlib gir",
            use="GLIB-2.0", include="GLIB-2.0",
            source="example.c", target="example")
    bld.program(use="example", source="test.c", target="test")
