#! /usr/bin/env python

def options(opt):
    opt.load("compiler_c")

def configure(cnf):
    cnf.load("compiler_c")
    cnf.check_cfg(package="glib-2.0", args='--cflags --libs')
    cnf.load("gir", tooldir="..")

def build(bld):
    bld(features="c cshlib gir", use="GLIB-2.0", scan="example.h",
            source="example.c", target="example")
    bld.program(use="example", source="test.c", target="test")
