#! /usr/bin/env python

def options(opt):
    opt.load("compiler_c")

def configure(cnf):
    cnf.load("compiler_c")
    cnf.check_cfg(package="glib-2.0", args='--cflags --libs')

def build(bld):
    bld.shlib(use="GLIB-2.0", source="example.c", target="example")
